Fix/sni 6056 set background removal parameter
cloudinary/cloudinary_ios pull request #348
Opened 2021-11-29 19:47 UTC by AlexPinhasov

### Brief Summary of Changes

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [x] New feature
- [x] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [ ] Yes
- [x] No

#### Reviewer, please note:

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

2021-11-30 08:28 UTC, const-cloudinary commented
@AlexPinhasov , please add unit tests.

2021-11-30 20:43 UTC, AlexPinhasov commented
@const-cloudinary Unit test added.

2021-12-02 13:19 UTC, const-cloudinary requested changes

2021-12-02 13:19 UTC, const-cloudinary commented on Example/Tests/NetworkTests/UploaderTests/UploaderTests.swift
> +        params.setBackgroundRemoval("cloudinary_ai")
Please see:
https://github.com/cloudinary/pycloudinary/blob/73d84511eb18d2f4198d6375059a5d94716fc0c4/test/test_uploader.py#L781

2021-12-02 16:34 UTC, AlexPinhasov commented on Example/Tests/NetworkTests/UploaderTests/UploaderTests.swift
> +        params.setBackgroundRemoval("cloudinary_ai")
Done

2021-12-03 14:17 UTC, merged