Fix/readme carthage
cloudinary/cloudinary_ios pull request #351
Opened 2021-12-16 09:32 UTC by adimiz1

### Brief Summary of Changes
I've updated the README.md file and the .gitingore file.

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [x] Refactoring
- [ ] New feature
- [ ] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [ ] Yes
- [x] No

#### Reviewer, please note:
Nothing major, updated the Readme.md to contain installation instructions for carthage (which I personally verified to work)
And added OSX files to the .gitignore file so they wont slip into the repo.

#### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation. (I changed the documentation)
- [ ] I ran the full test suite before pushing the changes and all the tests pass.

2021-12-16 20:41 UTC, asisayag2 approved these changes
Kululu🍾

2021-12-16 20:46 UTC, const-cloudinary requested changes

2021-12-16 20:46 UTC, const-cloudinary commented on README.md
> +    * File > Add Pakcages... >
```suggestion
    * File > Add Packages... >
```

2021-12-16 20:46 UTC, const-cloudinary commented on README.md
> +  pod 'Cloudinary', '~> 3.1.0'
We don't want to update this number on every new(minor/patch) version released, let's reconsider this.

2021-12-16 20:46 UTC, const-cloudinary commented on .gitignore
> +*.DS_Store
Please include this in a separate PR, this change is not related to "Carthage readme" update

2021-12-19 06:20 UTC, adimiz1 commented
1. Fixed type on Packages
2. Fixed version number back to 3.0 in both CocoaPods and Carthage
3. Removed the .gitignore change into anohter branch.

2021-12-20 14:02 UTC, const-cloudinary commented on README.md
> +
Please add a brief description

2021-12-20 14:37 UTC, merged