Fix expression normalize for user variables
cloudinary/cloudinary_ios pull request #378
Opened 2022-03-08 07:41 UTC by GiniAppsPartners

### Brief Summary of Changes
Fix normalize function to not trim user variables such as: $width to $w
Add tests to verify edge cases

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [ ] New feature
- [x] Bug fix
- [x] Adds more tests

#### Are tests included?
- [x] Yes
- [ ] No

#### Reviewer, please note:

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

2022-03-20 10:35 UTC, adimiz1 approved these changes

2022-03-22 13:25 UTC, const-cloudinary requested changes

2022-03-22 14:58 UTC, GiniAppsPartners commented on Cloudinary/Classes/Core/Features/Helpers/CLDExpression.swift
> +        let value = removeExtraDashes(from: replaceAllUnicodeChars(in: currentValue))
Done

2022-03-23 14:19 UTC, const-cloudinary approved these changes

2022-03-27 08:27 UTC, merged